"""empty message

Revision ID: 0456cd22aac1
Revises: 3ccfb17e5280
Create Date: 2025-05-31 13:01:59.316787

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0456cd22aac1'
down_revision = '3ccfb17e5280'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('home_work',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('product_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.Text(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('created_date', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('modified_date', mysql.INTEGER(unsigned=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_home_work_created_date'), 'home_work', ['created_date'], unique=False)
    op.add_column('answer', sa.Column('question_id', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'answer', 'question', ['question_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.add_column('question', sa.Column('home_work_id', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'question', 'home_work', ['home_work_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.drop_column('question', 'home_work_id')
    op.drop_constraint(None, 'answer', type_='foreignkey')
    op.drop_column('answer', 'question_id')
    op.drop_index(op.f('ix_home_work_created_date'), table_name='home_work')
    op.drop_table('home_work')
    # ### end Alembic commands ###
