"""empty message

Revision ID: 2a06995b6d2a
Revises: 557b8192f6c5
Create Date: 2025-06-05 16:49:05.061595

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2a06995b6d2a'
down_revision = '557b8192f6c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doc_course',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('product_id', sa.String(length=50), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('file_name', sa.String(length=255, collation='utf8mb4_vietnamese_ci'), nullable=True),
    sa.Column('created_date', mysql.INTEGER(unsigned=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doc_course_created_date'), 'doc_course', ['created_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_doc_course_created_date'), table_name='doc_course')
    op.drop_table('doc_course')
    # ### end Alembic commands ###
