"""empty message

Revision ID: 37c72fa1a297
Revises: 
Create Date: 2025-05-28 21:12:59.911949

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '37c72fa1a297'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('file_name', sa.String(length=255, collation='utf8mb4_vietnamese_ci'), nullable=True),
    sa.Column('created_date', mysql.INTEGER(unsigned=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_created_date'), 'files', ['created_date'], unique=False)
    op.create_table('type_product',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('key', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('created_date', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('modified_date', mysql.INTEGER(unsigned=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_type_product_created_date'), 'type_product', ['created_date'], unique=False)
    op.create_table('file_link',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('file_id', sa.String(length=50), nullable=True),
    sa.Column('table_id', sa.String(length=50), nullable=True),
    sa.Column('table_type', sa.String(length=50), nullable=False),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('created_date', mysql.INTEGER(unsigned=True), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_link_created_date'), 'file_link', ['created_date'], unique=False)
    op.create_table('product',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.Text(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('describe', sa.Text(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('type_product_id', sa.String(length=50), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=False),
    sa.Column('price', sa.BigInteger(), nullable=True),
    sa.Column('created_date', sa.Integer(), nullable=True),
    sa.Column('modified_date', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['type_product_id'], ['type_product.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100, collation='utf8mb4_vietnamese_ci'), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('gender', sa.Boolean(), nullable=False),
    sa.Column('full_name', sa.String(length=100, collation='utf8mb4_vietnamese_ci'), nullable=False),
    sa.Column('avatar_id', sa.String(length=50), nullable=True),
    sa.Column('birthday', sa.DATE(), nullable=False),
    sa.Column('created_date', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('modified_date', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['avatar_id'], ['files.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_created_date'), 'user', ['created_date'], unique=False)
    op.create_table('cart_items',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('created_date', sa.Integer(), nullable=True),
    sa.Column('modified_date', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('product_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_order',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('created_date', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verity_code',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('limit', mysql.INTEGER(unsigned=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_online',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('order_payment_id', sa.String(length=100), nullable=False),
    sa.Column('request_payment_id', sa.String(length=50), nullable=False),
    sa.Column('session_order_id', sa.String(length=50), nullable=True),
    sa.Column('result_payment', sa.JSON(), nullable=True),
    sa.Column('status_payment', sa.Boolean(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('created_date', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_order_id'], ['session_order.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_order_cart_items',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('created_date', sa.Integer(), nullable=True),
    sa.Column('cart_id', sa.String(length=50), nullable=False),
    sa.Column('session_order_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['cart_items.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_order_id'], ['session_order.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('count', sa.BigInteger(), nullable=True),
    sa.Column('created_date', sa.Integer(), nullable=True),
    sa.Column('modified_date', sa.Integer(), nullable=True),
    sa.Column('payment_online_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['payment_online_id'], ['payment_online.id'], onupdate='SET NULL', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchased_courses',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('product_id', sa.String(length=50), nullable=True),
    sa.Column('order_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('created_date', sa.Integer(), nullable=True),
    sa.Column('modified_date', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], onupdate='SET NULL', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchased_courses')
    op.drop_table('orders')
    op.drop_table('session_order_cart_items')
    op.drop_table('payment_online')
    op.drop_table('verity_code')
    op.drop_table('session_order')
    op.drop_table('cart_items')
    op.drop_index(op.f('ix_user_created_date'), table_name='user')
    op.drop_table('user')
    op.drop_table('product')
    op.drop_index(op.f('ix_file_link_created_date'), table_name='file_link')
    op.drop_table('file_link')
    op.drop_index(op.f('ix_type_product_created_date'), table_name='type_product')
    op.drop_table('type_product')
    op.drop_index(op.f('ix_files_created_date'), table_name='files')
    op.drop_table('files')
    # ### end Alembic commands ###
