"""empty message

Revision ID: 3ccfb17e5280
Revises: e3077667511a
Create Date: 2025-05-29 21:36:11.310395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ccfb17e5280'
down_revision = 'e3077667511a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_course', sa.Column('product_id', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'session_course', 'product', ['product_id'], ['id'], onupdate='SET NULL', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'session_course', type_='foreignkey')
    op.drop_column('session_course', 'product_id')
    # ### end Alembic commands ###
