"""empty message

Revision ID: 78e958bdbac7
Revises: db11da14a74b
Create Date: 2025-06-09 22:50:27.692873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78e958bdbac7'
down_revision = 'db11da14a74b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_course', sa.Column('file_id', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'session_course', 'files', ['file_id'], ['id'], onupdate='SET NULL', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'session_course', type_='foreignkey')
    op.drop_column('session_course', 'file_id')
    # ### end Alembic commands ###
