"""empty message

Revision ID: 7db88a121a91
Revises: 37c72fa1a297
Create Date: 2025-05-28 22:42:52.615943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7db88a121a91'
down_revision = '37c72fa1a297'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchased_courses', sa.Column('price', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchased_courses', 'price')
    # ### end Alembic commands ###
