"""empty message

Revision ID: db11da14a74b
Revises: 2a06995b6d2a
Create Date: 2025-06-09 21:58:01.165412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db11da14a74b'
down_revision = '2a06995b6d2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_course', sa.Column('file_name', sa.Text(collation='utf8mb4_unicode_ci'), nullable=True))
    op.add_column('user_do_home_work', sa.Column('is_congratulation', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_do_home_work', 'is_congratulation')
    op.drop_column('session_course', 'file_name')
    # ### end Alembic commands ###
