"""empty message

Revision ID: e3077667511a
Revises: 7db88a121a91
Create Date: 2025-05-29 14:51:49.855456

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e3077667511a'
down_revision = '7db88a121a91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('answer', sa.Text(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('result_answer', sa.Boolean(), nullable=False),
    sa.Column('created_date', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('modified_date', mysql.INTEGER(unsigned=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answer_created_date'), 'answer', ['created_date'], unique=False)
    op.create_table('session_course',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.Text(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('created_date', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('url', sa.Text(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_course_created_date'), 'session_course', ['created_date'], unique=False)
    op.create_table('question',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('question', sa.Text(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('product_id', sa.String(length=50), nullable=True),
    sa.Column('created_date', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('modified_date', mysql.INTEGER(unsigned=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_created_date'), 'question', ['created_date'], unique=False)
    op.create_table('user_answer',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('question_id', sa.String(length=50), nullable=True),
    sa.Column('answer_id', sa.String(length=50), nullable=True),
    sa.Column('created_date', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('modified_date', mysql.INTEGER(unsigned=True), nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['answer.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_answer_created_date'), 'user_answer', ['created_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_answer_created_date'), table_name='user_answer')
    op.drop_table('user_answer')
    op.drop_index(op.f('ix_question_created_date'), table_name='question')
    op.drop_table('question')
    op.drop_index(op.f('ix_session_course_created_date'), table_name='session_course')
    op.drop_table('session_course')
    op.drop_index(op.f('ix_answer_created_date'), table_name='answer')
    op.drop_table('answer')
    # ### end Alembic commands ###
